import type {ReactNode} from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/widgets/header";

export const metadata: Metadata = {
  title: "Phones",
  description: "Generated by Anvar",
};

interface RootLayoutType {
    children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {

    return (
        <html lang="en">
            <body>
                <Header />
                <div style={{padding: "16px"}}>
                        {children}
                </div>
            </body>
        </html>
  );
}
