import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/src/widgets/header';

export const metadata: Metadata = {
    title: 'Phones',
    description: 'Generated by Anvar',
};

interface RootLayoutType {
    children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutType) => (
    <html lang="en">
        <body>
            <Header />
            <div>
                {children}
            </div>
        </body>
    </html>
);

export default RootLayout;
